#index:
#    path: /
#    controller: App\Controller\DefaultController::index
homepage:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /login
        permanent: true
app_logout:
    path: /logout